(()=>{'use strict';
const slides=[...document.querySelectorAll('.slide')],jump=document.querySelector('#jump');
let current=0, overview=false;document.body.classList.add('js');
function show(index,update=true){current=Math.max(0,Math.min(slides.length-1,index));slides.forEach((s,i)=>{s.classList.toggle('active',i===current);s.setAttribute('aria-hidden',String(!overview&&i!==current));});document.querySelectorAll('[data-note]').forEach((n,i)=>n.classList.toggle('active',i===current));jump.value=String(current+1);document.querySelector('#counter').textContent=`${current+1} / ${slides.length}`;document.querySelector('#prev').disabled=current===0;document.querySelector('#next').disabled=current===slides.length-1;document.querySelector('#progress').style.width=`${(current+1)/slides.length*100}%`;if(update)history.replaceState(null,'',`#slaid-${current+1}`);}
function fromHash(){const match=location.hash.match(/^#slaid-(\d+)$/);show(match?Number(match[1])-1:0,false);}
function toggleOverview(){overview=!overview;document.body.classList.toggle('overview',overview);document.querySelector('#overview').setAttribute('aria-pressed',String(overview));show(current);if(!overview)window.scrollTo(0,0);}
function toggleNotes(){const panel=document.querySelector('#note-panel');panel.hidden=!panel.hidden;document.querySelector('#notes').setAttribute('aria-pressed',String(!panel.hidden));}
async function fullscreen(){try{if(document.fullscreenElement)await document.exitFullscreen();else await document.body.requestFullscreen();}catch{document.querySelector('#fullscreen').textContent='Gunakan menu pelayar';}}
document.querySelector('#next').onclick=()=>show(current+1);document.querySelector('#prev').onclick=()=>show(current-1);jump.onchange=()=>show(Number(jump.value)-1);document.querySelector('#overview').onclick=toggleOverview;document.querySelector('#notes').onclick=toggleNotes;document.querySelector('#close-notes').onclick=toggleNotes;document.querySelector('#fullscreen').onclick=fullscreen;document.querySelector('#print').onclick=()=>window.print();
window.addEventListener('hashchange',fromHash);
document.addEventListener('keydown',e=>{if(e.altKey||e.ctrlKey||e.metaKey||/INPUT|TEXTAREA|SELECT/.test(e.target.tagName))return;const k=e.key.toLowerCase();if(e.target.closest('button,a')&&(k===' '||k==='enter'))return;if(['arrowright','pagedown',' '].includes(k)){e.preventDefault();show(current+1);}else if(['arrowleft','pageup'].includes(k)){e.preventDefault();show(current-1);}else if(k==='home'){e.preventDefault();show(0);}else if(k==='end'){e.preventDefault();show(slides.length-1);}else if(k==='o')toggleOverview();else if(k==='n')toggleNotes();else if(k==='f')fullscreen();else if(k==='escape'){if(overview)toggleOverview();if(!document.querySelector('#note-panel').hidden)toggleNotes();}});
slides.forEach((slide,i)=>slide.addEventListener('click',()=>{if(overview){show(i);toggleOverview();}}));
let touch=null;document.querySelector('#deck').addEventListener('touchstart',e=>{if(e.touches.length===1)touch={x:e.touches[0].clientX,y:e.touches[0].clientY};},{passive:true});document.querySelector('#deck').addEventListener('touchend',e=>{if(!touch||overview)return;const dx=e.changedTouches[0].clientX-touch.x,dy=e.changedTouches[0].clientY-touch.y;if(Math.abs(dx)>65&&Math.abs(dx)>Math.abs(dy)*1.6)show(current+(dx<0?1:-1));touch=null;},{passive:true});
fromHash();
})();
